name: second_activity
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

isar_version: &isar_version 3.1.0+1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  freezed_annotation: ^2.4.1
  flutter_hooks: ^0.20.4
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  isar: *isar_version
  isar_flutter_libs: *isar_version
  equatable: ^2.0.5
  path_provider: ^2.1.2
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  build_runner: ^2.4.6
  freezed: ^2.4.1
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/svgs/